language: php
<<<<<<< HEAD
php:
  -7.1
before_script:
  - composer install --dev --prefer-source --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
=======


>>>>>>> ab7645d5cb71b3020aa8e61600e7aaff1cae6ce8
script:
  - vendor/bin/phpunit tests/Fearure/ExampleTest.php
